// Generated by purs bundle 0.12.0
var PS = {};
(function(exports) {
  "use strict";

  exports.arrayApply = function(fs) {
    return function(xs) {
      var l = fs.length;
      var k = xs.length;
      var result = new Array(l * k);
      var n = 0;
      for (var i = 0; i < l; i++) {
        var f = fs[i];
        for (var j = 0; j < k; j++) {
          result[n++] = f(xs[j]);
        }
      }
      return result;
    };
  };
})((PS["Control.Apply"] = PS["Control.Apply"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Semigroupoid = function(compose) {
    this.compose = compose;
  };
  var semigroupoidFn = new Semigroupoid(function(f) {
    return function(g) {
      return function(x) {
        return f(g(x));
      };
    };
  });
  var compose = function(dict) {
    return dict.compose;
  };
  exports["compose"] = compose;
  exports["Semigroupoid"] = Semigroupoid;
  exports["semigroupoidFn"] = semigroupoidFn;
})((PS["Control.Semigroupoid"] = PS["Control.Semigroupoid"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Category = function(Semigroupoid0, identity) {
    this.Semigroupoid0 = Semigroupoid0;
    this.identity = identity;
  };
  var identity = function(dict) {
    return dict.identity;
  };
  var categoryFn = new Category(
    function() {
      return Control_Semigroupoid.semigroupoidFn;
    },
    function(x) {
      return x;
    }
  );
  exports["Category"] = Category;
  exports["identity"] = identity;
  exports["categoryFn"] = categoryFn;
})((PS["Control.Category"] = PS["Control.Category"] || {}));
(function(exports) {
  "use strict";

  exports.arrayMap = function(f) {
    return function(arr) {
      var l = arr.length;
      var result = new Array(l);
      for (var i = 0; i < l; i++) {
        result[i] = f(arr[i]);
      }
      return result;
    };
  };
})((PS["Data.Functor"] = PS["Data.Functor"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Functor"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Function = PS["Data.Function"];
  var Data_Unit = PS["Data.Unit"];
  var Functor = function(map) {
    this.map = map;
  };
  var map = function(dict) {
    return dict.map;
  };
  var functorArray = new Functor($foreign.arrayMap);
  exports["Functor"] = Functor;
  exports["map"] = map;
  exports["functorArray"] = functorArray;
})((PS["Data.Functor"] = PS["Data.Functor"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Control.Apply"];
  var Control_Category = PS["Control.Category"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Apply = function(Functor0, apply) {
    this.Functor0 = Functor0;
    this.apply = apply;
  };
  var applyArray = new Apply(function() {
    return Data_Functor.functorArray;
  }, $foreign.arrayApply);
  var apply = function(dict) {
    return dict.apply;
  };
  exports["Apply"] = Apply;
  exports["apply"] = apply;
  exports["applyArray"] = applyArray;
})((PS["Control.Apply"] = PS["Control.Apply"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Apply = PS["Control.Apply"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Unit = PS["Data.Unit"];
  var Applicative = function(Apply0, pure) {
    this.Apply0 = Apply0;
    this.pure = pure;
  };
  var pure = function(dict) {
    return dict.pure;
  };
  var applicativeArray = new Applicative(
    function() {
      return Control_Apply.applyArray;
    },
    function(x) {
      return [x];
    }
  );
  exports["Applicative"] = Applicative;
  exports["pure"] = pure;
  exports["applicativeArray"] = applicativeArray;
})((PS["Control.Applicative"] = PS["Control.Applicative"] || {}));
(function(exports) {
  "use strict";

  exports.arrayBind = function(arr) {
    return function(f) {
      var result = [];
      for (var i = 0, l = arr.length; i < l; i++) {
        Array.prototype.push.apply(result, f(arr[i]));
      }
      return result;
    };
  };
})((PS["Control.Bind"] = PS["Control.Bind"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Control.Bind"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Category = PS["Control.Category"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Unit = PS["Data.Unit"];
  var Bind = function(Apply0, bind) {
    this.Apply0 = Apply0;
    this.bind = bind;
  };
  var bindArray = new Bind(function() {
    return Control_Apply.applyArray;
  }, $foreign.arrayBind);
  var bind = function(dict) {
    return dict.bind;
  };
  exports["Bind"] = Bind;
  exports["bind"] = bind;
  exports["bindArray"] = bindArray;
})((PS["Control.Bind"] = PS["Control.Bind"] || {}));
(function(exports) {
  "use strict";

  //------------------------------------------------------------------------------
  // Array creation --------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.range = function(start) {
    return function(end) {
      var step = start > end ? -1 : 1;
      var result = new Array(step * (end - start) + 1);
      var i = start,
        n = 0;
      while (i !== end) {
        result[n++] = i;
        i += step;
      }
      result[n] = i;
      return result;
    };
  };
})((PS["Data.Array"] = PS["Data.Array"] || {}));
(function(exports) {
  "use strict";

  exports.foldrArray = function(f) {
    return function(init) {
      return function(xs) {
        var acc = init;
        var len = xs.length;
        for (var i = len - 1; i >= 0; i--) {
          acc = f(xs[i])(acc);
        }
        return acc;
      };
    };
  };

  exports.foldlArray = function(f) {
    return function(init) {
      return function(xs) {
        var acc = init;
        var len = xs.length;
        for (var i = 0; i < len; i++) {
          acc = f(acc)(xs[i]);
        }
        return acc;
      };
    };
  };
})((PS["Data.Foldable"] = PS["Data.Foldable"] || {}));
(function(exports) {
  "use strict";

  exports.intDegree = function(x) {
    return Math.min(Math.abs(x), 2147483647);
  };

  // See the Euclidean definition in
  // https://en.m.wikipedia.org/wiki/Modulo_operation.
  exports.intDiv = function(x) {
    return function(y) {
      if (y === 0) return 0;
      return y > 0 ? Math.floor(x / y) : -Math.floor(x / -y);
    };
  };

  exports.intMod = function(x) {
    return function(y) {
      if (y === 0) return 0;
      var yy = Math.abs(y);
      return ((x % yy) + yy) % yy;
    };
  };
})((PS["Data.EuclideanRing"] = PS["Data.EuclideanRing"] || {}));
(function(exports) {
  "use strict";

  exports.intSub = function(x) {
    return function(y) {
      /* jshint bitwise: false */
      return (x - y) | 0;
    };
  };
})((PS["Data.Ring"] = PS["Data.Ring"] || {}));
(function(exports) {
  "use strict";

  exports.intAdd = function(x) {
    return function(y) {
      /* jshint bitwise: false */
      return (x + y) | 0;
    };
  };

  exports.intMul = function(x) {
    return function(y) {
      /* jshint bitwise: false */
      return (x * y) | 0;
    };
  };
})((PS["Data.Semiring"] = PS["Data.Semiring"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Semiring"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_Row = PS["Type.Data.Row"];
  var Type_Data_RowList = PS["Type.Data.RowList"];
  var Semiring = function(add, mul, one, zero) {
    this.add = add;
    this.mul = mul;
    this.one = one;
    this.zero = zero;
  };
  var zero = function(dict) {
    return dict.zero;
  };
  var semiringInt = new Semiring($foreign.intAdd, $foreign.intMul, 1, 0);
  var one = function(dict) {
    return dict.one;
  };
  var mul = function(dict) {
    return dict.mul;
  };
  var add = function(dict) {
    return dict.add;
  };
  exports["Semiring"] = Semiring;
  exports["add"] = add;
  exports["zero"] = zero;
  exports["mul"] = mul;
  exports["one"] = one;
  exports["semiringInt"] = semiringInt;
})((PS["Data.Semiring"] = PS["Data.Semiring"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Ring"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];
  var Ring = function(Semiring0, sub) {
    this.Semiring0 = Semiring0;
    this.sub = sub;
  };
  var sub = function(dict) {
    return dict.sub;
  };
  var ringInt = new Ring(function() {
    return Data_Semiring.semiringInt;
  }, $foreign.intSub);
  exports["Ring"] = Ring;
  exports["sub"] = sub;
  exports["ringInt"] = ringInt;
})((PS["Data.Ring"] = PS["Data.Ring"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_Ring = PS["Data.Ring"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var CommutativeRing = function(Ring0) {
    this.Ring0 = Ring0;
  };
  var commutativeRingInt = new CommutativeRing(function() {
    return Data_Ring.ringInt;
  });
  exports["CommutativeRing"] = CommutativeRing;
  exports["commutativeRingInt"] = commutativeRingInt;
})((PS["Data.CommutativeRing"] = PS["Data.CommutativeRing"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.EuclideanRing"];
  var Data_BooleanAlgebra = PS["Data.BooleanAlgebra"];
  var Data_CommutativeRing = PS["Data.CommutativeRing"];
  var Data_Eq = PS["Data.Eq"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semiring = PS["Data.Semiring"];
  var EuclideanRing = function(CommutativeRing0, degree, div, mod) {
    this.CommutativeRing0 = CommutativeRing0;
    this.degree = degree;
    this.div = div;
    this.mod = mod;
  };
  var mod = function(dict) {
    return dict.mod;
  };
  var euclideanRingInt = new EuclideanRing(
    function() {
      return Data_CommutativeRing.commutativeRingInt;
    },
    $foreign.intDegree,
    $foreign.intDiv,
    $foreign.intMod
  );
  var div = function(dict) {
    return dict.div;
  };
  var degree = function(dict) {
    return dict.degree;
  };
  exports["EuclideanRing"] = EuclideanRing;
  exports["degree"] = degree;
  exports["div"] = div;
  exports["mod"] = mod;
  exports["euclideanRingInt"] = euclideanRingInt;
})((PS["Data.EuclideanRing"] = PS["Data.EuclideanRing"] || {}));
(function(exports) {
  "use strict";

  exports.concatString = function(s1) {
    return function(s2) {
      return s1 + s2;
    };
  };
})((PS["Data.Semigroup"] = PS["Data.Semigroup"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Semigroup"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var Data_Void = PS["Data.Void"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];
  var Semigroup = function(append) {
    this.append = append;
  };
  var semigroupString = new Semigroup($foreign.concatString);
  var append = function(dict) {
    return dict.append;
  };
  exports["Semigroup"] = Semigroup;
  exports["append"] = append;
  exports["semigroupString"] = semigroupString;
})((PS["Data.Semigroup"] = PS["Data.Semigroup"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_Boolean = PS["Data.Boolean"];
  var Data_Eq = PS["Data.Eq"];
  var Data_EuclideanRing = PS["Data.EuclideanRing"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];
  var Monoid = function(Semigroup0, mempty) {
    this.Semigroup0 = Semigroup0;
    this.mempty = mempty;
  };
  var mempty = function(dict) {
    return dict.mempty;
  };
  exports["Monoid"] = Monoid;
  exports["mempty"] = mempty;
})((PS["Data.Monoid"] = PS["Data.Monoid"] || {}));
(function(exports) {
  "use strict";

  exports.showIntImpl = function(n) {
    return n.toString();
  };
})((PS["Data.Show"] = PS["Data.Show"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Show"];
  var Data_Symbol = PS["Data.Symbol"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];
  var Show = function(show) {
    this.show = show;
  };
  var showInt = new Show($foreign.showIntImpl);
  var show = function(dict) {
    return dict.show;
  };
  exports["Show"] = Show;
  exports["show"] = show;
  exports["showInt"] = showInt;
})((PS["Data.Show"] = PS["Data.Show"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Category = PS["Control.Category"];
  var Control_Extend = PS["Control.Extend"];
  var Control_Monad = PS["Control.Monad"];
  var Control_MonadZero = PS["Control.MonadZero"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Bounded = PS["Data.Bounded"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Show = PS["Data.Show"];
  var Data_Unit = PS["Data.Unit"];
  var Prelude = PS["Prelude"];
  var Nothing = (function() {
    function Nothing() {}
    Nothing.value = new Nothing();
    return Nothing;
  })();
  var Just = (function() {
    function Just(value0) {
      this.value0 = value0;
    }
    Just.create = function(value0) {
      return new Just(value0);
    };
    return Just;
  })();
  var semigroupMaybe = function(dictSemigroup) {
    return new Data_Semigroup.Semigroup(function(v) {
      return function(v1) {
        if (v instanceof Nothing) {
          return v1;
        }
        if (v1 instanceof Nothing) {
          return v;
        }
        if (v instanceof Just && v1 instanceof Just) {
          return new Just(
            Data_Semigroup.append(dictSemigroup)(v.value0)(v1.value0)
          );
        }
        throw new Error(
          "Failed pattern match at Data.Maybe line 175, column 1 - line 175, column 62: " +
            [v.constructor.name, v1.constructor.name]
        );
      };
    });
  };
  var monoidMaybe = function(dictSemigroup) {
    return new Data_Monoid.Monoid(function() {
      return semigroupMaybe(dictSemigroup);
    }, Nothing.value);
  };
  var maybe = function(v) {
    return function(v1) {
      return function(v2) {
        if (v2 instanceof Nothing) {
          return v;
        }
        if (v2 instanceof Just) {
          return v1(v2.value0);
        }
        throw new Error(
          "Failed pattern match at Data.Maybe line 218, column 1 - line 218, column 51: " +
            [v.constructor.name, v1.constructor.name, v2.constructor.name]
        );
      };
    };
  };
  var fromMaybe = function(a) {
    return maybe(a)(Control_Category.identity(Control_Category.categoryFn));
  };
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;
  exports["maybe"] = maybe;
  exports["fromMaybe"] = fromMaybe;
  exports["semigroupMaybe"] = semigroupMaybe;
  exports["monoidMaybe"] = monoidMaybe;
})((PS["Data.Maybe"] = PS["Data.Maybe"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Foldable"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Category = PS["Control.Category"];
  var Control_Plus = PS["Control.Plus"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Maybe_Last = PS["Data.Maybe.Last"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Monoid_Additive = PS["Data.Monoid.Additive"];
  var Data_Monoid_Conj = PS["Data.Monoid.Conj"];
  var Data_Monoid_Disj = PS["Data.Monoid.Disj"];
  var Data_Monoid_Dual = PS["Data.Monoid.Dual"];
  var Data_Monoid_Endo = PS["Data.Monoid.Endo"];
  var Data_Monoid_Multiplicative = PS["Data.Monoid.Multiplicative"];
  var Data_Newtype = PS["Data.Newtype"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Unit = PS["Data.Unit"];
  var Prelude = PS["Prelude"];
  var Foldable = function(foldMap, foldl, foldr) {
    this.foldMap = foldMap;
    this.foldl = foldl;
    this.foldr = foldr;
  };
  var foldr = function(dict) {
    return dict.foldr;
  };
  var foldl = function(dict) {
    return dict.foldl;
  };
  var foldMapDefaultR = function(dictFoldable) {
    return function(dictMonoid) {
      return function(f) {
        return foldr(dictFoldable)(function(x) {
          return function(acc) {
            return Data_Semigroup.append(dictMonoid.Semigroup0())(f(x))(acc);
          };
        })(Data_Monoid.mempty(dictMonoid));
      };
    };
  };
  var foldableArray = new Foldable(
    function(dictMonoid) {
      return foldMapDefaultR(foldableArray)(dictMonoid);
    },
    $foreign.foldlArray,
    $foreign.foldrArray
  );
  var foldMap = function(dict) {
    return dict.foldMap;
  };
  exports["Foldable"] = Foldable;
  exports["foldr"] = foldr;
  exports["foldl"] = foldl;
  exports["foldMap"] = foldMap;
  exports["foldMapDefaultR"] = foldMapDefaultR;
  exports["foldableArray"] = foldableArray;
})((PS["Data.Foldable"] = PS["Data.Foldable"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Array"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Category = PS["Control.Category"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_Monad_Rec_Class = PS["Control.Monad.Rec.Class"];
  var Control_Monad_ST = PS["Control.Monad.ST"];
  var Control_Monad_ST_Internal = PS["Control.Monad.ST.Internal"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Array_NonEmpty_Internal = PS["Data.Array.NonEmpty.Internal"];
  var Data_Array_ST = PS["Data.Array.ST"];
  var Data_Array_ST_Iterator = PS["Data.Array.ST.Iterator"];
  var Data_Boolean = PS["Data.Boolean"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Partial_Unsafe = PS["Partial.Unsafe"];
  var Prelude = PS["Prelude"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];
  exports["range"] = $foreign.range;
})((PS["Data.Array"] = PS["Data.Array"] || {}));
(function(exports) {
  "use strict";

  exports.log = function(s) {
    return function() {
      console.log(s);
      return {};
    };
  };
})((PS["Effect.Console"] = PS["Effect.Console"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Effect.Console"];
  var Data_Show = PS["Data.Show"];
  var Data_Unit = PS["Data.Unit"];
  var Effect = PS["Effect"];
  exports["log"] = $foreign.log;
})((PS["Effect.Console"] = PS["Effect.Console"] || {}));
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Array = PS["Data.Array"];
  var Data_Eq = PS["Data.Eq"];
  var Data_EuclideanRing = PS["Data.EuclideanRing"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Show = PS["Data.Show"];
  var Effect_Console = PS["Effect.Console"];
  var Prelude = PS["Prelude"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];
  var range2D = function(w) {
    return function(h) {
      return Control_Bind.bind(Control_Bind.bindArray)(
        Data_Array.range(0)((h - 1) | 0)
      )(function(v) {
        return Control_Applicative.pure(
          Control_Applicative.applicativeArray
        )(Data_Array.range((((v * w) | 0) + 1) | 0)((((v + 1) | 0) * w) | 0));
      });
    };
  };
  var game = function(rules$prime) {
    return function(i) {
      var applyRule = function(f) {
        return f(i);
      };
      return Data_Maybe.fromMaybe(Data_Show.show(Data_Show.showInt)(i))(
        Data_Foldable.foldMap(Data_Foldable.foldableArray)(
          Data_Maybe.monoidMaybe(Data_Semigroup.semigroupString)
        )(applyRule)(rules$prime)
      );
    };
  };
  var divisBy = function(y) {
    return function(x) {
      return (
        Data_EuclideanRing.mod(Data_EuclideanRing.euclideanRingInt)(x)(y) === 0
      );
    };
  };
  var cond = function(test) {
    return function(s) {
      return function(i) {
        var $2 = test(i);
        if ($2) {
          return new Data_Maybe.Just(s);
        }
        return Data_Maybe.Nothing.value;
      };
    };
  };
  var rules = [
    cond(divisBy(3))("\ud83d\udc2d"),
    cond(divisBy(5))("\ud83d\udc31"),
    cond(divisBy(5))("\ud83d\udc36")
  ];
  var main = (function() {
    var mapmap = function($3) {
      return Data_Functor.map(Data_Functor.functorArray)(
        Data_Functor.map(Data_Functor.functorArray)($3)
      );
    };
    var logAny = function($4) {
      return Effect_Console.log($4);
    };
    return logAny(mapmap(game(rules))(range2D(10)(10)));
  })();
  exports["cond"] = cond;
  exports["game"] = game;
  exports["divisBy"] = divisBy;
  exports["rules"] = rules;
  exports["range2D"] = range2D;
  exports["main"] = main;
})((PS["Main"] = PS["Main"] || {}));
PS["Main"].main();
