// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Int$BsAbstract = require("bs-abstract/lib/js/src/implementations/Int.bs.js");
var Array$BsAbstract = require("bs-abstract/lib/js/src/implementations/Array.bs.js");
var Option$BsAbstract = require("bs-abstract/lib/js/src/implementations/Option.bs.js");
var Function$BsAbstract = require("bs-abstract/lib/js/src/implementations/Function.bs.js");
var Functors$BsAbstract = require("bs-abstract/lib/js/src/utilities/Functors.bs.js");

var FoldMapAOS = Curry._1(
  Array$BsAbstract.Foldable[/* Fold_Map */ 2],
  Functors$BsAbstract.OptionF[/* String */ 3][/* Monoid */ 2]
);

function cond(test, s, i) {
  var match = Curry._1(test, i);
  if (match) {
    return s;
  }
}

function game(rules, i) {
  var applyRule = function(f) {
    return Curry._1(f, i);
  };
  return Curry._2(
    Option$BsAbstract.Infix[/* |? */ 8],
    Int$BsAbstract.Show[/* show */ 0](i),
    Curry._2(FoldMapAOS[/* fold_map */ 0], applyRule, rules)
  );
}

function divis(by, i) {
  return Caml_int32.mod_(i, by) === 0;
}

var partial_arg = "🐭";

var partial_arg$1 = "🐱";

var partial_arg$2 = "🐶";

var rules = /* array */ [
  function(param) {
    return cond(
      function(param) {
        return divis(3, param);
      },
      partial_arg,
      param
    );
  },
  function(param) {
    return cond(
      function(param) {
        return divis(5, param);
      },
      partial_arg$1,
      param
    );
  },
  function(param) {
    return cond(
      function(param) {
        return divis(7, param);
      },
      partial_arg$2,
      param
    );
  }
];

function $neg$neg$caret(start, finish) {
  return Belt_Array.range(start, (finish - 1) | 0);
}

function range2D(w, h) {
  var row = function(y) {
    return Curry._2(
      Array$BsAbstract.Infix[/* <$> */ 7],
      function(param) {
        var y$1 = y;
        var x = param;
        return (((Caml_int32.imul(y$1, w) + x) | 0) + 1) | 0;
      },
      $neg$neg$caret(0, w)
    );
  };
  return Curry._2(
    Array$BsAbstract.Infix[/* <$> */ 7],
    row,
    $neg$neg$caret(0, h)
  );
}

console.log(
  Curry._4(
    Function$BsAbstract.Infix[/* <. */ 0],
    Array$BsAbstract.Functor[/* map */ 0],
    Array$BsAbstract.Functor[/* map */ 0],
    function(param) {
      return game(rules, param);
    },
    range2D(10, 10)
  )
);

exports.FoldMapAOS = FoldMapAOS;
exports.cond = cond;
exports.game = game;
exports.divis = divis;
exports.rules = rules;
exports.$neg$neg$caret = $neg$neg$caret;
exports.range2D = range2D;
/* FoldMapAOS Not a pure module */
